SELECT
  ORG.EDRPOU,
  ORG.SHORTNAME,
  --ORG.INDTAXNUM,
  CASE WHEN TRIM(ORG.INDTAXNUM) <> '100000000000' AND TRIM(ORG.INDTAXNUM) <> '' 
    THEN 'ПДВ' 
    ELSE ''
  END AS vat,
  ORG.DEPT,
  CARD.PERDATE,
  --CARD.SENDSTT,
  CAST(CARD.MODDATE AS DATE) AS MODDATE,
  CARDSENDSTT.NAME,
  --CARD.STATUS,
  CARDSTATUS.NAME AS StatusName,
  FORM.CHARCODE, 
  --FORM.NAME,
  ''
FROM 
  ORG
LEFT JOIN CARD
  ON CARD.IDORG = ORG.Code 
  AND CARD.PERDATE = DATE '2025-12-01'
LEFT JOIN FORM
  ON FORM.CODE = CARD.FORM
LEFT JOIN CARDSTATUS
  ON CARDSTATUS.CODE = CARD.STATUS 
LEFT JOIN CARDSENDSTT
  ON CARDSENDSTT.CODE = CARD.SENDSTT 
WHERE
  TRUE  
  --AND ORG.EDRPOU = '45747371' 
  --AND FORM.CHARCODE IN ('j0200126', 'j0500110')
  AND (ORG.DEPT <> '0' OR ORG.DEPT IS NULL) 
  --AND ORG.INDTAXNUM <> ''
  --AND (CARD.STATUS <> 2 OR CARD.IDORG IS NULL)
ORDER BY   
    StatusName,
    ORG.SHORTNAME 
    

SELECT
  ORG.EDRPOU,
  ORG.DEPT,
  ORG.SHORTNAME,
  --ORG.INDTAXNUM,
  CASE WHEN TRIM(ORG.INDTAXNUM) <> '100000000000' AND TRIM(ORG.INDTAXNUM) <> ''
   --THEN 'ПДВ'
   THEN CAST('ПДВ' AS VARCHAR(10))
   ELSE ''
  END AS vat,
  CARD.PERDATE,
  --CARD.SENDSTT,
  CARDSENDSTT.NAME,
  FORM.CHARCODE,
  --CARD.STATUS,
  CARD.MODDATE,
  --CAST(CARD.MODDATE AS DATE) AS MODDATE,
  CARDSTATUS.NAME AS StatusName
FROM
  ORG
LEFT JOIN CARD
  ON CARD.IDORG = ORG.Code
  AND CARD.PERDATE = DATE %_PERDATE
  AND CARD.FORM > 0
  AND CARD.IDPARENT IS NULL
LEFT JOIN FORM
  ON FORM.CODE = CARD.FORM
  AND LOWER(FORM.CHARCODE) = :_CHARCODE
LEFT JOIN CARDSTATUS
  ON CARDSTATUS.CODE = CARD.STATUS
LEFT JOIN CARDSENDSTT
  ON CARDSENDSTT.CODE = CARD.SENDSTT
WHERE
  TRUE
  --AND ORG.EDRPOU = '37938319'
  --AND LOWER(FORM.CHARCODE) IN ('j0200126', 'j0500110', 'j0100129', 'j0209513')
  AND (ORG.DEPT <> '0' OR ORG.DEPT IS NULL)
  --AND ORG.INDTAXNUM <> ''
  --AND (CARD.STATUS <> 2 OR CARD.IDORG IS NULL)
ORDER BY
	StatusName,
	ORG.SHORTNAME

SELECT
    ORG.EDRPOU,
    ORG.DEPT,
    ORG.SHORTNAME,
    C.PERDATE,
    C.CARDSENDSTT_NAME,
    C.CHARCODE,
    C.MODDATE,
    C.StatusName
FROM
    ORG
LEFT JOIN (
    SELECT
        CARD.IDORG,
        CARD.PERDATE,
        CARDSENDSTT.NAME AS CARDSENDSTT_NAME,
        FORM.CHARCODE,
        CARD.MODDATE,
        CARDSTATUS.NAME AS StatusName
    FROM CARD
    LEFT JOIN FORM
        ON FORM.CODE = CARD.FORM
    LEFT JOIN CARDSTATUS
        ON CARDSTATUS.CODE = CARD.STATUS
    LEFT JOIN CARDSENDSTT
        ON CARDSENDSTT.CODE = CARD.SENDSTT
    WHERE
        CARD.PERDATE = DATE '2025-12-01'
        AND CARD.IDPARENT IS NULL
        AND CARD.FORM > 0
        AND LOWER(FORM.CHARCODE) = 'j0500110'
) C
    ON C.IDORG = ORG.CODE
WHERE
    ORG.DEPT IS NULL OR ORG.DEPT <> '0'
ORDER BY
    C.StatusName,
    ORG.SHORTNAME;
