SELECT
    ORG.EDRPOU,
    ORG.DEPT,
    ORG.SHORTNAME,
    ORG.INDTAXNUM,
    CASE WHEN TRIM(ORG.INDTAXNUM) <> '100000000000' AND TRIM(ORG.INDTAXNUM) <> ''
      THEN CAST('ПДВ' AS VARCHAR(10))
      ELSE ''
    END AS vat,
    T2.PERDATE,
    CAST(T2.PERDATE AS VARCHAR(10)) AS PERDATE_STR,
    T2.CHARCODE,
    T2.CARDSENDSTT_NAME,
    T2.MODDATE,
    T2.CARDSTATUS_NAME,
    T2.XMLVALS
FROM
    ORG
LEFT JOIN (
    SELECT
        CARD.IDORG,
        CARD.PERDATE,
        CARDSENDSTT.NAME AS CARDSENDSTT_NAME,
        FORM.CHARCODE,
        CAST(CARD.MODDATE AS DATE) AS MODDATE,
        CARDSTATUS.NAME AS CARDSTATUS_NAME,
        CARDBLOB.XMLVALS
    FROM
      CARD
    LEFT JOIN FORM
        ON FORM.CODE = CARD.FORM
    LEFT JOIN CARDSTATUS
        ON CARDSTATUS.CODE = CARD.STATUS
    LEFT JOIN CARDSENDSTT
        ON CARDSENDSTT.CODE = CARD.SENDSTT
    LEFT JOIN CARDBLOB
        ON CARDBLOB.CODE = CARD.CODE
     LEFT JOIN FJ0500106_MAIN TFJ ON TFJ.CARDCODE = CARD.CODE
    WHERE
        (CARD.PERDATE = DATE '2026-07-01')
        AND (CARD.IDPARENT IS NULL)
        AND (CARD.FORM > 0)
        AND (CARD.INTRASH = 0)
) T2
    ON T2.IDORG = ORG.CODE
WHERE
    (ORG.DEPT IS NULL OR ORG.DEPT <> '0')
ORDER BY
  CARDSTATUS_NAME ASC
